services:
  - type: web
    name: telegram-bot-lanation
    runtime: node
    repo: https://github.com/juniorrrrr345/LAMAINVRTR
    branch: main
    buildCommand: npm install
    startCommand: node bot-webhook.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: PORT
        generateValue: true
    healthCheckPath: /health
    autoDeploy: true